package ai

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/sirupsen/logrus"
)

// Config holds the configuration for the AI service
type Config struct {
	APIEndpoint     string
	APIKey          string
	DefaultModel    string
	TimeoutSeconds  int
}

// ChatRequest represents a request for AI chat completion
type ChatRequest struct {
	Model    string    `json:"model,omitempty"`
	Messages []Message `json:"messages"`
	Temperature float64 `json:"temperature,omitempty"`
	MaxTokens int     `json:"max_tokens,omitempty"`
	Stream   bool    `json:"stream,omitempty"`
}

// Message represents a chat message
type Message struct {
	Role    string `json:"role"`    // "system", "user", or "assistant"
	Content string `json:"content"`
}

// ChatResponse represents the response from AI chat completion
type ChatResponse struct {
	ID      string `json:"id"`
	Object  string `json:"object"`
	Created int64  `json:"created"`
	Model   string `json:"model"`
	Choices []Choice `json:"choices"`
	Usage   Usage  `json:"usage"`
}

// Choice represents a single choice in the completion
type Choice struct {
	Index   int     `json:"index"`
	Message Message `json:"message"`
	FinishReason string `json:"finish_reason,omitempty"`
}

// Usage represents token usage statistics
type Usage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

// Service provides AI chat completion functionality
type Service struct {
	logger  *logrus.Entry
	client  *http.Client
	config  *Config
}

// NewService creates a new AI service instance
func NewService(logger *logrus.Logger, config *Config) *Service {
	if config == nil {
		config = &Config{}
	}
	// Set defaults
	if config.TimeoutSeconds == 0 {
		config.TimeoutSeconds = 30
	}

	return &Service{
		logger:  logger.WithField("component", "ai_service"),
		client:  &http.Client{Timeout: time.Duration(config.TimeoutSeconds) * time.Second},
		config:  config,
	}
}

// ChatCompletion sends a chat completion request to the AI service
func (s *Service) ChatCompletion(ctx context.Context, req ChatRequest) (*ChatResponse, error) {
	s.logger.WithFields(logrus.Fields{
		"model":   req.Model,
		"message_count": len(req.Messages),
	}).Info("Processing AI chat completion request")

	// If no API endpoint is configured, return a mock response for development
	if s.config.APIEndpoint == "" {
		return s.generateMockResponse(req), nil
	}

	// Prepare the request
	reqBody, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", s.config.APIEndpoint, bytes.NewReader(reqBody))
	if err != nil {
		return nil, fmt.Errorf("failed to create HTTP request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", "application/json")
	if s.config.APIKey != "" {
		httpReq.Header.Set("Authorization", "Bearer "+s.config.APIKey)
	}

	// Make the HTTP request
	resp, err := s.client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to make HTTP request: %w", err)
	}
	defer resp.Body.Close()

	// Check response status
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("API returned non-OK status: %d", resp.StatusCode)
	}

	// Decode the response
	var chatResp ChatResponse
	if err := json.NewDecoder(resp.Body).Decode(&chatResp); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	return &chatResp, nil
}

// generateMockResponse creates a mock AI response for development/testing
func (s *Service) generateMockResponse(req ChatRequest) *ChatResponse {
	// Create a simple echo response for the last user message
	var lastUserMessage string
	for i := len(req.Messages) - 1; i >= 0; i-- {
		if req.Messages[i].Role == "user" {
			lastUserMessage = req.Messages[i].Content
			break
		}
	}

	if lastUserMessage == "" {
		lastUserMessage = "Hello! How can I assist you today?"
	}

	// Simple response that echoes back with a prefix
	responseContent := fmt.Sprintf("You said: \"%s\"\n\nThis is a simulated AI response. In a production environment, this would be generated by a real AI model like GPT-3.5, %s", lastUserMessage, lastUserMessage)

	return &ChatResponse{
		ID:      fmt.Sprintf("chatcmpl-%d", time.Now().UnixNano()),
		Object:  "chat.completion",
		Created: time.Now().Unix(),
		Model:   req.Model,
		Choices: []Choice{
			{
				Index: 0,
				Message: Message{
					Role:    "assistant",
					Content: responseContent,
				},
				FinishReason: "stop",
			},
		},
		Usage: Usage{
			PromptTokens:     len(lastUserMessage) / 4, // Rough estimate
			CompletionTokens: len(responseContent) / 4, // Rough estimate
			TotalTokens:      (len(lastUserMessage) + len(responseContent)) / 4,
		},
	}
}